---
  - name: stoping apache2
    service:
      name: apache2
      state: stopped  
  - name: remove php-common-5.4.16-46.el7.x86_64
    apt:
      state: absent
      name: php-common-5.4.16-46.el7.x86_64
     
  - name: Install php
    apt:
      state: latest
      name: "{{item}}"

    with_items:
      - php
      - php-mbstring
      - php-pear
      - php-mysql
      - php-gd
      - php-xml
      - php-bcmath
      - php-fpm

  - name: Install nginx
    apt:
      state: present
      name: nginx
  - name: starting nginx
    service:
      name: nginx
      state: started

  - name: Criar zabbix.conf
    file:
      path: "/etc/nginx/conf.d/zabbix.conf"
      state: touch

  - name: Editar zabbix.conf
    copy:
      dest: "/etc/nginx/conf.d/zabbix.conf"
      content: |
       server {
        listen       80;
        listen       [::]:80;
        server_name  _;
        root         /usr/share/nginx/html/;
        index        index.php;
        # Load configuration files for the default server block.
        # include /etc/nginx/default.d/*.conf;

        location ~ \.php$ {
            root           /usr/share/nginx/html/;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include        fastcgi_params;
         }

        error_page 404 /404.html;
            location = /40x.html {
         }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
          }
         }

  - name: modificar php.ini 
    template:
      src: "php.ini.j2"
      dest: "/etc/php.ini"

  - name: modificar nginx.conf
    template:
      src: "nginx.conf.j2"
      dest: "/etc/nginx/nginx.conf"



