---
  - name: Install epel-release
    yum:
      state: present
      name: epel-release

  - name: install repo mysql
    yum:
      name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
      state: present
      update_cache: yes

  - name: Install mysql-server
    yum:
      state: present
      name: ['mysql-server', 'mysql']

  - name: starting mysql
    service:
      name: mysqld
      state: started 

  - name: Enable mysql
    service:
      name: mysqld
      enabled: yes

  - name: Install python-pip
    yum: 
      state: present
      name: python-pip
  
  - pip:
      name: pymysql
  
  - mysql_user:
      name: ''
      host: localhost
      state: absent

  - mysql_user:
      name: ''
      host_all: yes
      state: absent

  - mysql_user:
      name: "{{ db_user_name }}"
      password: "{{ db_password }}"
      priv: '*.*:ALL,GRANT'
      state: present       
    
  - name: restarting mysql
    service:
      name: mysqld
      state: restarted 

  - name: Create a new database with name 'zabbix'
    mysql_db:
      name: "{{ db_name }}"
      state: present