---
  - name: Install a .deb package from the internet.
    apt:
      deb: https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb

  - name: Install zabbix server - zabbix web
    apt:
      state: present
      name: "{{item}}"

    with_items:
      - zabbix-server-mysql
      - zabbix-frontend-php      

  - name: importando dados
    shell: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -u{{ db_user_name }} {{ db_name }} -p{{ db_password }}

  - name: zabbix web para o nginx
    shell:  cp -R /usr/share/zabbix/ /usr/share/nginx/html/

  - name: permitindo acesso do nginx a pasta zabbix
    shell:  chmod 0777 /usr/share/nginx/html/zabbix    

  # - name: permitindo acesso do nginx a pasta zabbix
  #   shell:  chown nginx:nginx /usr/share/nginx/html/zabbix 
  
  - name: edit zabbix_server.conf
    template: 
      src: "zabbix_server.conf.j2"
      dest: "/etc/zabbix/zabbix_server.conf"

  - name: starting zabbix-server
    service:
      name: zabbix-server
      state: started

  - name: restarting nginx
    service:
      name: nginx
      state: restarted


    